INSERT INTO site VALUES ('INSA LYON', '32, BANANA LES BAINS');
INSERT INTO server VALUES ('3IF',1337,1337,42,'OMG NASA','INSA LYON','Linux',NULL);
INSERT INTO instance VALUES ('3IF','3IF','ORACLE','42.0');
INSERT INTO base_de_donnee VALUES ('3IF','3IF');